### ISSUE TITLE
shutsdown

### ISSUE THREAD

**Issue by wackoamd1** [matt-harp/PopupTotals#1]
after a while the mod just shutsdown , when u restart the game it is working again , 
very strange but it just stops working while playing a while

which is bad because it is a great QoL mod

**Comment by matt-harp** [comment]
If you could gather any sort of logs or errors when this occurs it would be helpful to be able to reproduce the issue, otherwise I can't fix it if I don't know what the issue is. I haven't run into the mod spontaneously not working myself.
